In [ ]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

# arquivo = '/content/drive/MyDrive/FIAP/FIAP/BASE DE DADOS PEDE 2024 - DATATHON.xlsx'
arquivo = '/content/drive/MyDrive/Colab Notebooks/Datathon Fase 5/FIAP/BASE DE DADOS PEDE 2024 - DATATHON.xlsx'

Mounted at /content/drive

In [ ]:
# Unificando as abas
df_dict = pd.read_excel(arquivo, sheet_name=None)

# Carregar as bases
df_2022 = df_dict['PEDE2022'].copy()
df_2023 = df_dict['PEDE2023'].copy()
df_2024 = df_dict['PEDE2024'].copy()

In [ ]:
# Analisando as informações dos DataFrames

print(f"2022: {df_2022.shape}")
print(f"2023: {df_2023.shape}")
print(f"2024: {df_2024.shape}")

2022: (860, 42)
2023: (1014, 48)
2024: (1156, 50)

In [ ]:
# Analisando colunas de 2022 individualmente

df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    object
 1   Fase                   860 non-null    int64
 2   Turma                  860 non-null    object
 3   Nome                   860 non-null    object
 4   Ano nasc               860 non-null    int64
 5   Idade 22               860 non-null    int64
 6   Gênero                 860 non-null    object
 7   Ano ingresso           860 non-null    int64
 8   Instituição de ensino  860 non-null    object
 9   Pedra 20               323 non-null    object
 10  Pedra 21               462 non-null    object
 11  Pedra 22               860 non-null    object
 12  INDE 22                860 non-null    float64
 13  Cg                     860 non-null    int64
 14  Cf                     860 non-null    int64
 15  Ct                     860 non-null    int64
 16  Nº Av                  860 non-null    int64
 17  Avaliador1             860 non-null    object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             860 non-null    object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             534 non-null    object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             310 non-null    object
 24  Rec Av4                296 non-null    object
 25  IAA                    860 non-null    float64
 26  IEG                    860 non-null    float64
 27  IPS                    860 non-null    float64
 28  Rec Psicologia         860 non-null    object
 29  IDA                    860 non-null    float64
 30  Matem                  858 non-null    float64
 31  Portug                 858 non-null    float64
 32  Inglês                 283 non-null    float64
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    860 non-null    float64
 36  IAN                    860 non-null    float64
 37  Fase ideal             860 non-null    object
 38  Defas                  860 non-null    int64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
dtypes: float64(10), int64(9), object(23)
memory usage: 282.3+ KB

In [ ]:
# Analisando colunas de 2023 individualmente

df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   object
 1   Fase                   1014 non-null   object
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    object
 4   Turma                  1014 non-null   object
 5   Nome Anonimizado       1014 non-null   object
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   object
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   object
 11  Pedra 20               240 non-null    object
 12  Pedra 21               335 non-null    object
 13  Pedra 22               600 non-null    object
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    float64
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    object
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    object
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    float64
 30  IEG                    938 non-null    float64
 31  IPS                    945 non-null    float64
 32  IPP                    938 non-null    float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    937 non-null    float64
 35  Mat                    937 non-null    float64
 36  Por                    937 non-null    float64
 37  Ing                    334 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    938 non-null    float64
 41  IAN                    1014 non-null   float64
 42  Fase Ideal             1014 non-null   object
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(29), int64(2), object(17)
memory usage: 380.4+ KB

In [ ]:
# Analisando colunas de 2024 individualmente

df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   object
 1   Fase                   1156 non-null   object
 2   INDE 2024              1092 non-null   object
 3   Pedra 2024             1092 non-null   object
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   object
 6   Data de Nasc           1156 non-null   datetime64[ns]
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   object
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   object
 11  Pedra 20               191 non-null    object
 12  Pedra 21               264 non-null    object
 13  Pedra 22               472 non-null    object
 14  Pedra 23               690 non-null    object
 15  INDE 22                472 non-null    float64
 16  INDE 23                690 non-null    float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    object
 26  Avaliador4             407 non-null    object
 27  Avaliador5             148 non-null    object
 28  Avaliador6             6 non-null      object
 29  IAA                    1054 non-null   float64
 30  IEG                    1156 non-null   float64
 31  IPS                    1054 non-null   float64
 32  IPP                    1054 non-null   float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1055 non-null   float64
 35  Mat                    1051 non-null   float64
 36  Por                    1050 non-null   float64
 37  Ing                    474 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1054 non-null   float64
 41  IAN                    1156 non-null   float64
 42  Fase Ideal             1156 non-null   object
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   object
 48  Ativo/ Inativo         1156 non-null   object
 49  Ativo/ Inativo.1       1156 non-null   object
dtypes: datetime64[ns](1), float64(23), int64(4), object(22)
memory usage: 451.7+ KB

In [ ]:
# Iniciando padronização

df_2022_tratado = df_2022.copy()

# Selecionar colunas
df_2022_tratado = df_2022_tratado[['RA', 'Gênero', 'Fase', 'Defas', 'Pedra 22', 'IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPV', 'INDE 22']]

# Padronizar nomes de colunas
df_2022_tratado = df_2022_tratado.rename(columns={
    'Gênero': 'Genero',
    'Pedra 22': 'Pedra',
    'Defas': 'Defasagem',
    'INDE 22': 'INDE'
})

df_2022_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RA         860 non-null    object
 1   Genero     860 non-null    object
 2   Fase       860 non-null    int64
 3   Defasagem  860 non-null    int64
 4   Pedra      860 non-null    object
 5   IAN        860 non-null    float64
 6   IDA        860 non-null    float64
 7   IEG        860 non-null    float64
 8   IAA        860 non-null    float64
 9   IPS        860 non-null    float64
 10  IPV        860 non-null    float64
 11  INDE       860 non-null    float64
dtypes: float64(7), int64(2), object(3)
memory usage: 80.8+ KB

In [ ]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   object
 1   Fase                   1014 non-null   object
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    object
 4   Turma                  1014 non-null   object
 5   Nome Anonimizado       1014 non-null   object
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   object
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   object
 11  Pedra 20               240 non-null    object
 12  Pedra 21               335 non-null    object
 13  Pedra 22               600 non-null    object
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    float64
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    object
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    object
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    float64
 30  IEG                    938 non-null    float64
 31  IPS                    945 non-null    float64
 32  IPP                    938 non-null    float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    937 non-null    float64
 35  Mat                    937 non-null    float64
 36  Por                    937 non-null    float64
 37  Ing                    334 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    938 non-null    float64
 41  IAN                    1014 non-null   float64
 42  Fase Ideal             1014 non-null   object
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(29), int64(2), object(17)
memory usage: 380.4+ KB

In [ ]:
df_2023_tratado = df_2023.copy()

# Selecionar colunas
df_2023_tratado = df_2023_tratado[['RA', 'Gênero', 'Fase', 'Defasagem', 'Pedra 2023', 'IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPV', 'INDE 2023', 'IPP']]

# Padronizar nomes de colunas
df_2023_tratado = df_2023_tratado.rename(columns={
    'Gênero': 'Genero',
    'Pedra 2023': 'Pedra',
    'INDE 2023': 'INDE'
})

df_2023_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RA         1014 non-null   object
 1   Genero     1014 non-null   object
 2   Fase       1014 non-null   object
 3   Defasagem  1014 non-null   int64
 4   Pedra      931 non-null    object
 5   IAN        1014 non-null   float64
 6   IDA        937 non-null    float64
 7   IEG        938 non-null    float64
 8   IAA        951 non-null    float64
 9   IPS        945 non-null    float64
 10  IPV        938 non-null    float64
 11  INDE       931 non-null    float64
 12  IPP        938 non-null    float64
dtypes: float64(8), int64(1), object(4)
memory usage: 103.1+ KB

In [ ]:
# Retirar nulos de df_2023_tratado

df_2023_tratado = df_2023_tratado.dropna()

df_2023_tratado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 931 entries, 0 to 937
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RA         931 non-null    object
 1   Genero     931 non-null    object
 2   Fase       931 non-null    object
 3   Defasagem  931 non-null    int64
 4   Pedra      931 non-null    object
 5   IAN        931 non-null    float64
 6   IDA        931 non-null    float64
 7   IEG        931 non-null    float64
 8   IAA        931 non-null    float64
 9   IPS        931 non-null    float64
 10  IPV        931 non-null    float64
 11  INDE       931 non-null    float64
 12  IPP        931 non-null    float64
dtypes: float64(8), int64(1), object(4)
memory usage: 101.8+ KB

In [ ]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   object
 1   Fase                   1156 non-null   object
 2   INDE 2024              1092 non-null   object
 3   Pedra 2024             1092 non-null   object
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   object
 6   Data de Nasc           1156 non-null   datetime64[ns]
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   object
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   object
 11  Pedra 20               191 non-null    object
 12  Pedra 21               264 non-null    object
 13  Pedra 22               472 non-null    object
 14  Pedra 23               690 non-null    object
 15  INDE 22                472 non-null    float64
 16  INDE 23                690 non-null    float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    object
 26  Avaliador4             407 non-null    object
 27  Avaliador5             148 non-null    object
 28  Avaliador6             6 non-null      object
 29  IAA                    1054 non-null   float64
 30  IEG                    1156 non-null   float64
 31  IPS                    1054 non-null   float64
 32  IPP                    1054 non-null   float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1055 non-null   float64
 35  Mat                    1051 non-null   float64
 36  Por                    1050 non-null   float64
 37  Ing                    474 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1054 non-null   float64
 41  IAN                    1156 non-null   float64
 42  Fase Ideal             1156 non-null   object
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   object
 48  Ativo/ Inativo         1156 non-null   object
 49  Ativo/ Inativo.1       1156 non-null   object
dtypes: datetime64[ns](1), float64(23), int64(4), object(22)
memory usage: 451.7+ KB

In [ ]:
df_2024_tratado = df_2024.copy()

# Selecionar colunas
df_2024_tratado = df_2024_tratado[['RA', 'Gênero', 'Fase', 'Defasagem', 'Pedra 2024', 'IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPV', 'INDE 2024', 'IPP']]

# Padronizar nomes de colunas
df_2024_tratado = df_2024_tratado.rename(columns={
    'Gênero': 'Genero',
    'Pedra 2024': 'Pedra',
    'INDE 2024': 'INDE'
})

df_2024_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RA         1156 non-null   object
 1   Genero     1156 non-null   object
 2   Fase       1156 non-null   object
 3   Defasagem  1156 non-null   int64
 4   Pedra      1092 non-null   object
 5   IAN        1156 non-null   float64
 6   IDA        1055 non-null   float64
 7   IEG        1156 non-null   float64
 8   IAA        1054 non-null   float64
 9   IPS        1054 non-null   float64
 10  IPV        1054 non-null   float64
 11  INDE       1092 non-null   object
 12  IPP        1054 non-null   float64
dtypes: float64(7), int64(1), object(5)
memory usage: 117.5+ KB

In [ ]:
# Retirar nulos de df_2024_tratado

df_2024_tratado = df_2024_tratado.dropna()

df_2024_tratado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1054 entries, 0 to 1053
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RA         1054 non-null   object
 1   Genero     1054 non-null   object
 2   Fase       1054 non-null   object
 3   Defasagem  1054 non-null   int64
 4   Pedra      1054 non-null   object
 5   IAN        1054 non-null   float64
 6   IDA        1054 non-null   float64
 7   IEG        1054 non-null   float64
 8   IAA        1054 non-null   float64
 9   IPS        1054 non-null   float64
 10  IPV        1054 non-null   float64
 11  INDE       1054 non-null   object
 12  IPP        1054 non-null   float64
dtypes: float64(7), int64(1), object(5)
memory usage: 115.3+ KB

In [ ]:
# Verificação das colunas padronizadas

print(df_2022_tratado.columns)
print(df_2023_tratado.columns)
print(df_2024_tratado.columns)

Index(['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra', 'IAN', 'IDA', 'IEG',
       'IAA', 'IPS', 'IPV', 'INDE'],
      dtype='object')
Index(['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra', 'IAN', 'IDA', 'IEG',
       'IAA', 'IPS', 'IPV', 'INDE', 'IPP'],
      dtype='object')
Index(['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra', 'IAN', 'IDA', 'IEG',
       'IAA', 'IPS', 'IPV', 'INDE', 'IPP'],
      dtype='object')

In [ ]:
import numpy as np

# Criando a coluna IPP em 2022 com valores fictícios (Zerados) para padronizar
df_2022_tratado['IPP'] = np.nan

# AnoRef para identificar o ano de referência dos registros de cada base
df_2022_tratado['AnoRef'] = 2022
df_2023_tratado['AnoRef'] = 2023
df_2024_tratado['AnoRef'] = 2024

# Reordenar as colunas para que fiquem exatamente na mesma ordem dos outros anos
colunas_padrao = df_2024_tratado.columns.tolist()
df_2022_tratado = df_2022_tratado[colunas_padrao]
df_2023_tratado = df_2023_tratado[colunas_padrao]

In [ ]:
# Listar as colunas

print(df_2022_tratado.columns)
print(df_2023_tratado.columns)
print(df_2024_tratado.columns)

Index(['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra', 'IAN', 'IDA', 'IEG',
       'IAA', 'IPS', 'IPV', 'INDE', 'IPP', 'AnoRef'],
      dtype='object')
Index(['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra', 'IAN', 'IDA', 'IEG',
       'IAA', 'IPS', 'IPV', 'INDE', 'IPP', 'AnoRef'],
      dtype='object')
Index(['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra', 'IAN', 'IDA', 'IEG',
       'IAA', 'IPS', 'IPV', 'INDE', 'IPP', 'AnoRef'],
      dtype='object')

In [ ]:
# Concatenar os dataframes
df_combinado = pd.concat([df_2022_tratado, df_2023_tratado, df_2024_tratado], ignore_index=True)

print("Dataframe combinado criado com sucesso!")
print("\nPrimeiras 5 linhas do df_combinado:")
display(df_combinado.head())

print("\nInformações do df_combinado:")
df_combinado.info()

Dataframe combinado criado com sucesso!

Primeiras 5 linhas do df_combinado:

,RA,Genero,Fase,Defasagem,Pedra,IAN,IDA,IEG,IAA,IPS,IPV,INDE,IPP,AnoRef
0,RA-1,Menina,7,-1,Quartzo,5.0,4.0,4.1,8.3,5.6,7.278,5.783,NaN,2022
1,RA-2,Menina,7,0,Ametista,10.0,6.8,5.2,8.8,6.3,6.778,7.055,NaN,2022
2,RA-3,Menina,7,0,Ágata,10.0,5.6,7.9,0.0,5.6,7.556,6.591,NaN,2022
3,RA-4,Menino,7,0,Quartzo,10.0,5.0,4.5,8.8,5.6,5.278,5.951,NaN,2022
4,RA-5,Menina,7,0,Ametista,10.0,5.2,8.6,7.9,5.6,7.389,7.427,NaN,2022

Informações do df_combinado:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RA         2845 non-null   object
 1   Genero     2845 non-null   object
 2   Fase       2845 non-null   object
 3   Defasagem  2845 non-null   int64
 4   Pedra      2845 non-null   object
 5   IAN        2845 non-null   float64
 6   IDA        2845 non-null   float64
 7   IEG        2845 non-null   float64
 8   IAA        2845 non-null   float64
 9   IPS        2845 non-null   float64
 10  IPV        2845 non-null   float64
 11  INDE       2845 non-null   object
 12  IPP        1985 non-null   float64
 13  AnoRef     2845 non-null   int64
dtypes: float64(7), int64(2), object(5)
memory usage: 311.3+ KB

In [ ]:
#Analisando coluna RA

print(f"coluna 'RA': {df_combinado['RA'].dtype}")
print(f"Valores nulos: {df_combinado['RA'].isnull().sum()}")
print(f"Valores únicos: {df_combinado['RA'].nunique()}")
print("RA:")
display(df_combinado['RA'].unique()[:10])

coluna 'RA': object
Valores nulos: 0
Valores únicos: 1586
RA:

array(['RA-1', 'RA-2', 'RA-3', 'RA-4', 'RA-5', 'RA-6', 'RA-7', 'RA-8',
       'RA-9', 'RA-10'], dtype=object)

In [ ]:
# Transformando apenas em INT

df_combinado['RA'] = df_combinado['RA'].str.replace('RA-', '').astype(int)
print(f"coluna RA: {df_combinado['RA'].dtype}")
print("RA atualizada:")
display(df_combinado.head())

coluna RA: int64
RA atualizada:

,RA,Genero,Fase,Defasagem,Pedra,IAN,IDA,IEG,IAA,IPS,IPV,INDE,IPP,AnoRef
0,1,Menina,7,-1,Quartzo,5.0,4.0,4.1,8.3,5.6,7.278,5.783,NaN,2022
1,2,Menina,7,0,Ametista,10.0,6.8,5.2,8.8,6.3,6.778,7.055,NaN,2022
2,3,Menina,7,0,Ágata,10.0,5.6,7.9,0.0,5.6,7.556,6.591,NaN,2022
3,4,Menino,7,0,Quartzo,10.0,5.0,4.5,8.8,5.6,5.278,5.951,NaN,2022
4,5,Menina,7,0,Ametista,10.0,5.2,8.6,7.9,5.6,7.389,7.427,NaN,2022

In [ ]:
# Analisando a segunda coluna

print(f"Coluna Genero: {df_combinado['Genero'].dtype}")
print(f"Valores nulos: {df_combinado['Genero'].isnull().sum()}")
print(f"Quantidade Valores únicos: {df_combinado['Genero'].nunique()}")
print("Valores únicos:")
display(df_combinado['Genero'].unique())

Coluna Genero: object
Valores nulos: 0
Quantidade Valores únicos: 4
Valores únicos:

array(['Menina', 'Menino', 'Feminino', 'Masculino'], dtype=object)

In [ ]:
# Padronização de seus valores
df_combinado['Genero'] = df_combinado['Genero'].replace({
    'Menina': 'Feminino',
    'Menino': 'Masculino'
})

# Converter para categórico
df_combinado['Genero'] = df_combinado['Genero'].astype('category')

print("\nNovos valores únicos:")
display(df_combinado['Genero'].unique())
print(f"Tipo: {df_combinado['Genero'].dtype}")

Novos valores únicos:

['Feminino', 'Masculino']
Categories (2, object): ['Feminino', 'Masculino']

Tipo: category

In [ ]:
# Analisando a terceira coluna "Fase"

print(f"Tipo de dado da coluna 'Fase': {df_combinado['Fase'].dtype}")
print(f"Valores nulos na coluna 'Fase': {df_combinado['Fase'].isnull().sum()}")
print(f"Número de valores únicos na coluna 'Fase': {df_combinado['Fase'].nunique()}")
print("Valores únicos na coluna 'Fase':")
display(df_combinado['Fase'].unique())

Tipo de dado da coluna 'Fase': object
Valores nulos na coluna 'Fase': 0
Número de valores únicos na coluna 'Fase': 81
Valores únicos na coluna 'Fase':

array([7, 6, 5, 4, 3, 2, 1, 0, 'ALFA', 'FASE 1', 'FASE 2', 'FASE 3',
       'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', '1A', '1B', '1C', '1D',
       '1E', '1G', '1H', '1J', '1K', '1L', '1M', '1N', '1P', '1R', '2A',
       '2B', '2C', '2D', '2G', '2H', '2I', '2K', '2L', '2M', '2N', '2P',
       '2R', '2U', '3A', '3B', '3C', '3D', '3F', '3G', '3H', '3I', '3K',
       '3L', '3M', '3N', '3P', '3R', '3U', '4A', '4B', '4C', '4F', '4H',
       '4L', '4M', '4N', '4R', '5A', '5B', '5C', '5D', '5F', '5G', '5L',
       '5M', '5N', '6A', '6L', '7A', '7E'], dtype=object)

In [ ]:
 # De acordo com a documentação, as fases vão de ALFA a Fase 8. Aqui ALFA será considerado 0 e será feita a limpeza de dados não numéricos. As fases 1A, 1B... e casos semelhantes serão agrupados apenas pelo número.
df_combinado['Fase'] = df_combinado['Fase'].replace({
    'ALFA': '0', 'ALFA A': '0', 'ALFA B': '0', 'ALFA C': '0',
    'Alfa': '0', 'Alfa A': '0', 'Alfa B': '0', 'Alfa C': '0' # Adicionado variações com 'Alfa' minúsculo
})

# 2. Extrair a parte numérica

#df_combinado['Fase'] = df_combinado['Fase'].astype(str).str.extract(r'^(\d+)', expand=False)
df_combinado['Fase'] = df_combinado['Fase'].astype(str).str.extract(r'(\d+)', expand=False)

# 3. Converter a coluna 'Fase' para numérico, tratando erros para NaN
df_combinado['Fase'] = pd.to_numeric(df_combinado['Fase'], errors='coerce')

# Preencher NaNs restantes com 0 (assumindo que NaNs restantes são fases desconhecidas ou não aplicáveis)
df_combinado['Fase'] = df_combinado['Fase'].fillna(0)

# 4. Converter a coluna 'Fase' para o tipo categórico (já que as fases são categorias discretas)
df_combinado['Fase'] = df_combinado['Fase'].astype('category')

print("Coluna 'Fase' tratada e convertida para tipo categórico com sucesso!")
print(f"\nNovo tipo de dado da coluna 'Fase': {df_combinado['Fase'].dtype}")
print(f"Valores nulos na coluna 'Fase': {df_combinado['Fase'].isnull().sum()}")
display(df_combinado['Fase'].unique())

Coluna 'Fase' tratada e convertida para tipo categórico com sucesso!

Novo tipo de dado da coluna 'Fase': category
Valores nulos na coluna 'Fase': 0

[7, 6, 5, 4, 3, 2, 1, 0]
Categories (8, int64): [0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
# Coluna Defasagem

print(f"Tipo de dado da coluna 'Defasagem': {df_combinado['Defasagem'].dtype}")
print(f"Valores nulos na coluna 'Defasagem': {df_combinado['Defasagem'].isnull().sum()}")
print(f"Número de valores únicos na coluna 'Defasagem': {df_combinado['Defasagem'].nunique()}")
print("Valores únicos na coluna 'Defasagem':")
display(sorted(df_combinado['Defasagem'].unique()))

Tipo de dado da coluna 'Defasagem': int64
Valores nulos na coluna 'Defasagem': 0
Número de valores únicos na coluna 'Defasagem': 9
Valores únicos na coluna 'Defasagem':

[np.int64(-5),
 np.int64(-4),
 np.int64(-3),
 np.int64(-2),
 np.int64(-1),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3)]

In [ ]:
# 'Defasagem' para o tipo categórico
df_combinado['Defasagem'] = df_combinado['Defasagem'].astype('category')

print("Coluna 'Defasagem' convertida para tipo categórico com sucesso!")
print(f"Novo tipo de dado da coluna 'Defasagem': {df_combinado['Defasagem'].dtype}")
print("\nValores únicos na coluna 'Defasagem':")
display(df_combinado['Defasagem'].unique())

Coluna 'Defasagem' convertida para tipo categórico com sucesso!
Novo tipo de dado da coluna 'Defasagem': category

Valores únicos na coluna 'Defasagem':

[-1, 0, -2, -3, 2, 1, -4, -5, 3]
Categories (9, int64): [-5, -4, -3, -2, ..., 0, 1, 2, 3]

In [ ]:
#Analisando a coluna Pedra

print(f"Tipo de dado da coluna 'Pedra': {df_combinado['Pedra'].dtype}")
print(f"Valores nulos na coluna 'Pedra': {df_combinado['Pedra'].isnull().sum()}")
print(f"Número de valores únicos na coluna 'Pedra': {df_combinado['Pedra'].nunique()}")
print("Valores únicos na coluna 'Pedra':")
display(df_combinado['Pedra'].unique())

Tipo de dado da coluna 'Pedra': object
Valores nulos na coluna 'Pedra': 0
Número de valores únicos na coluna 'Pedra': 5
Valores únicos na coluna 'Pedra':

array(['Quartzo', 'Ametista', 'Ágata', 'Topázio', 'Agata'], dtype=object)

In [ ]:
# 1. Padronizar nomes
df_combinado['Pedra'] = df_combinado['Pedra'].replace('Agata', 'Ágata')

# Ordem de grandeza - conforme documentação
ordem_pedras = ['Quartzo', 'Ágata', 'Ametista', 'Topázio']

# Converter a coluna 'Pedra' para o tipo categórico ordenado
df_combinado['Pedra'] = pd.Categorical(df_combinado['Pedra'], categories=ordem_pedras, ordered=True)

print("Coluna 'Pedra' padronizada e convertida para tipo categórico ordenado com sucesso!")
print("\nNovos valores únicos na coluna 'Pedra' (ordenados):")
display(df_combinado['Pedra'].unique())
print(f"Novo tipo de dado da coluna 'Pedra': {df_combinado['Pedra'].dtype}")

Coluna 'Pedra' padronizada e convertida para tipo categórico ordenado com sucesso!

Novos valores únicos na coluna 'Pedra' (ordenados):

['Quartzo', 'Ametista', 'Ágata', 'Topázio']
Categories (4, object): ['Quartzo' < 'Ágata' < 'Ametista' < 'Topázio']

Novo tipo de dado da coluna 'Pedra': category

In [ ]:
# Verificando as colunas numéricas

print("Resumo estatístico do df_combinado:")
display(df_combinado.describe())

Resumo estatístico do df_combinado:

,RA,IAN,IDA,IEG,IAA,IPS,IPV,IPP,AnoRef
count,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,1985.000000,2845.000000
mean,707.295958,7.010545,6.376784,8.229802,7.926578,6.297762,7.545910,7.555974,2023.068190
std,421.094490,2.510504,1.957528,1.568487,2.617534,1.784413,1.085439,0.938275,0.817523
min,1.000000,2.500000,0.000000,0.000000,0.000000,2.500000,2.500000,2.500000,2022.000000
25%,369.000000,5.000000,5.100000,7.500000,7.900000,5.020000,6.966000,7.083333,2022.000000
50%,672.000000,5.000000,6.666667,8.654244,8.751000,7.500000,7.583000,7.500000,2023.000000
75%,1009.000000,10.000000,7.833333,9.400000,9.500000,7.510000,8.255000,8.125000,2024.000000
max,1632.000000,10.000000,10.000000,10.000000,10.002000,10.000000,10.010000,10.000000,2024.000000

In [ ]:
# Analisando INDE.

print(f"Tipo de dado da coluna 'INDE': {df_combinado['INDE'].dtype}")
print(f"Valores nulos na coluna 'INDE': {df_combinado['INDE'].isnull().sum()}")
print("Valores únicos na coluna 'INDE':")
display(df_combinado['INDE'].unique())

Tipo de dado da coluna 'INDE': object
Valores nulos na coluna 'INDE': 0
Valores únicos na coluna 'INDE':

array([5.783, 7.055, 6.591, ..., 7.449366666666667, 8.243183333333334,
       7.7887], dtype=object)

In [ ]:
# Convertendo INDE para numérico

df_combinado['INDE'] = pd.to_numeric(df_combinado['INDE'], errors='coerce')

print("Coluna 'INDE' convertida para numérica com sucesso!")
print(f"Novo tipo de dado da coluna 'INDE': {df_combinado['INDE'].dtype}")
print(f"Valores nulos na coluna 'INDE' após conversão: {df_combinado['INDE'].isnull().sum()}")

Coluna 'INDE' convertida para numérica com sucesso!
Novo tipo de dado da coluna 'INDE': float64
Valores nulos na coluna 'INDE' após conversão: 0

In [ ]:
print("Resumo estatístico do df_combinado após conversão de 'INDE':")
display(df_combinado.describe())

Resumo estatístico do df_combinado após conversão de 'INDE':

,RA,IAN,IDA,IEG,IAA,IPS,IPV,INDE,IPP,AnoRef
count,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,1985.000000,2845.000000
mean,707.295958,7.010545,6.376784,8.229802,7.926578,6.297762,7.545910,7.269915,7.555974,2023.068190
std,421.094490,2.510504,1.957528,1.568487,2.617534,1.784413,1.085439,0.991767,0.938275,0.817523
min,1.000000,2.500000,0.000000,0.000000,0.000000,2.500000,2.500000,3.032000,2.500000,2022.000000
25%,369.000000,5.000000,5.100000,7.500000,7.900000,5.020000,6.966000,6.675200,7.083333,2022.000000
50%,672.000000,5.000000,6.666667,8.654244,8.751000,7.500000,7.583000,7.388267,7.500000,2023.000000
75%,1009.000000,10.000000,7.833333,9.400000,9.500000,7.510000,8.255000,7.986867,8.125000,2024.000000
max,1632.000000,10.000000,10.000000,10.000000,10.002000,10.000000,10.010000,9.531325,10.000000,2024.000000

In [ ]:
display(df_combinado)

,RA,Genero,Fase,Defasagem,Pedra,IAN,IDA,IEG,IAA,IPS,IPV,INDE,IPP,AnoRef
0,1,Feminino,7,-1,Quartzo,5.0,4.000000,4.100000,8.300,5.6000,7.278,5.783000,NaN,2022
1,2,Feminino,7,0,Ametista,10.0,6.800000,5.200000,8.800,6.3000,6.778,7.055000,NaN,2022
2,3,Feminino,7,0,Ágata,10.0,5.600000,7.900000,0.000,5.6000,7.556,6.591000,NaN,2022
3,4,Masculino,7,0,Quartzo,10.0,5.000000,4.500000,8.800,5.6000,5.278,5.951000,NaN,2022
4,5,Feminino,7,0,Ametista,10.0,5.200000,8.600000,7.900,5.6000,7.389,7.427000,NaN,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,291,Masculino,7,2,Ametista,10.0,6.166667,9.737667,8.751,6.2600,7.500,7.931967,7.5,2024
2841,86,Masculino,7,0,Ametista,10.0,5.483333,9.704333,6.667,6.5700,7.500,7.611233,7.5,2024
2842,143,Masculino,7,2,Ametista,10.0,2.633333,9.920000,10.002,6.8850,7.500,7.449367,7.5,2024
2843,166,Masculino,7,1,Topázio,10.0,8.266667,9.246000,8.334,6.5725,7.500,8.243183,7.5,2024
2844,191,Masculino,7,2,Ametista,10.0,6.400000,9.571000,7.500,5.9450,7.500,7.788700,7.5,2024

#Precisamos incluir a coluna FASE no DF

In [ ]:
# 1. Selecionar colunas
cols = ['RA', 'Genero', 'Fase', 'Defasagem', 'Pedra',
        'IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPV', 'INDE', 'IPP', 'AnoRef']

df_knn = df_combinado[cols].copy()

# 2. Converter tipos
df_knn['Fase'] = df_knn['Fase'].astype(int)
df_knn['Defasagem'] = df_knn['Defasagem'].astype(int)
df_knn['Pedra'] = df_knn['Pedra'].astype('category').cat.codes

# 3. One-hot encoding
df_knn = pd.get_dummies(df_knn, columns=['Genero','Pedra'], dtype=int)

# 4. Separar ID
ids = df_knn['RA']
X = df_knn.drop(columns=['RA'])

# 5. Escalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 6. Imputar
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
X_imputed = imputer.fit_transform(X_scaled)

# 7. Voltar escala
X_final = scaler.inverse_transform(X_imputed)

df_final = pd.DataFrame(X_final, columns=X.columns)
df_final['RA'] = ids

# 8. Atualizar IPP no original
df_combinado = df_combinado.merge(
    df_final[['RA', 'IPP']], on='RA', how='left', suffixes=('', '_novo')
)

df_combinado['IPP'] = df_combinado['IPP_novo']
df_combinado.drop(columns=['IPP_novo'], inplace=True)

In [ ]:
display(df_knn)

,RA,Fase,Defasagem,IAN,IDA,IEG,IAA,IPS,IPV,INDE,IPP,AnoRef,Genero_Feminino,Genero_Masculino,Pedra_0,Pedra_1,Pedra_2,Pedra_3
0,1,7,-1,5.0,4.000000,4.100000,8.300,5.6000,7.278,5.783000,NaN,2022,1,0,1,0,0,0
1,2,7,0,10.0,6.800000,5.200000,8.800,6.3000,6.778,7.055000,NaN,2022,1,0,0,0,1,0
2,3,7,0,10.0,5.600000,7.900000,0.000,5.6000,7.556,6.591000,NaN,2022,1,0,0,1,0,0
3,4,7,0,10.0,5.000000,4.500000,8.800,5.6000,5.278,5.951000,NaN,2022,0,1,1,0,0,0
4,5,7,0,10.0,5.200000,8.600000,7.900,5.6000,7.389,7.427000,NaN,2022,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,291,7,2,10.0,6.166667,9.737667,8.751,6.2600,7.500,7.931967,7.5,2024,0,1,0,0,1,0
2841,86,7,0,10.0,5.483333,9.704333,6.667,6.5700,7.500,7.611233,7.5,2024,0,1,0,0,1,0
2842,143,7,2,10.0,2.633333,9.920000,10.002,6.8850,7.500,7.449367,7.5,2024,0,1,0,0,1,0
2843,166,7,1,10.0,8.266667,9.246000,8.334,6.5725,7.500,8.243183,7.5,2024,0,1,0,0,0,1
2844,191,7,2,10.0,6.400000,9.571000,7.500,5.9450,7.500,7.788700,7.5,2024,0,1,0,0,1,0

O código usa KNN + dados normalizados + variáveis transformadas para estimar valores faltantes de IPP, agora considerando também a variável Fase.

A coluna fase:
- Participa no cálculo de similaridade
- Influencia quem são os "vizinhos" no KNN
- Pode melhorar a qualidade da imputação

In [ ]:
print("Verificando as primeiras linhas do DataFrame combinado com fase e IPP atualizado:")
display(df_combinado.head())

Verificando as primeiras linhas do DataFrame combinado com fase e IPP atualizado:

,RA,Genero,Fase,Defasagem,Pedra,IAN,IDA,IEG,IAA,IPS,IPV,INDE,IPP,AnoRef
0,1,Feminino,7,-1,Quartzo,5.0,4.0,4.1,8.3,5.6,7.278,5.783,7.418750,2022
1,2,Feminino,7,0,Ametista,10.0,6.8,5.2,8.8,6.3,6.778,7.055,7.756250,2022
2,3,Feminino,7,0,Ágata,10.0,5.6,7.9,0.0,5.6,7.556,6.591,7.287500,2022
3,4,Masculino,7,0,Quartzo,10.0,5.0,4.5,8.8,5.6,5.278,5.951,6.702083,2022
4,5,Feminino,7,0,Ametista,10.0,5.2,8.6,7.9,5.6,7.389,7.427,7.500000,2022

In [ ]:
# file_path = '/content/drive/MyDrive/FIAP/FIAP/df_combinado.csv' # Você pode mudar o caminho e o nome do arquivo
file_path = '/content/drive/MyDrive/Colab Notebooks/Datathon Fase 5/FIAP/df_combinado.csv'
file_path_2 = '/content/drive/MyDrive/Colab Notebooks/Datathon Fase 5/FIAP/df_combinado_modelo.csv'

df_combinado.to_csv(file_path, index=False)
df_knn.to_csv(file_path_2, index=False)
print(f"DataFrame salvo em: {file_path}")

DataFrame salvo em: /content/drive/MyDrive/Colab Notebooks/Datathon Fase 5/FIAP/df_combinado.csv